use_frameworks!
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'
pod 'ZBarSDK', '~> 1.3.1'
pod 'libqrencode', '~> 3.4.2'
pod 'Masonry', '~> 0.6.4'
pod 'ZXingObjC', '~> 3.1.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'MJExtension', '~> 3.0.9'
